name: Build & Deploy Prueba
on:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:
    inputs:
        codigoApp:
          description: "Ingresar codigoApp"
          required: true
        nombreApp:
          description: "Ingresar nombreApp"
          required: true
jobs:
  build:
    #runs-on: ubuntu-20.04
    runs-on: ubuntu-latest
    steps:
      - name: inputs
        run: |
          echo "Mostrar input ${{ inputs.codigoApp}}"
          echo "Mostrar input ${{ inputs.nombreApp}}"     
      - name: variables  
        run: echo "mostrar variable de repositorio ${{ vars.S3_BUCKET }}"

      - name: Checkout
        uses: actions/checkout@v4.1.5
        
      - name: Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          # Version Spec of the version to use. Examples: 12.x
          node-version: 18.x
          
      - name: Install dependencies
        run: npm install
        
      - name: Build        
        run: npm run build
        
      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist          
          
