name: Build & Deploy AWS S3

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Build Job
  build:
    uses: estefa-932014/devops-templates/.github/workflows/build-s3-react.yml@main
    with:
      node-version: '18.x'
  deploy:
    needs: build
    uses: estefa-932014/devops-templates/.github/workflows/deploy-s3-react.yml@main
    secrets:
      access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
      secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  
      bucket_react: ${{ secrets.S3_BUCKET }}  
    with:
      bucket_react: ${{ vars.S3_BUCKET }}